# This automatically updates the dependencies on a daily basis. 

name: Auto-Update

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches: 
    - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: |
          echo "::group::Environment Information"
          echo "Node Version: $(node -v)"
          echo "NPM: $(npm -v)"
          echo "::endgroup::"
      - run: npm ci --save
      - run: npm update
      - run: npm audit fix
      # Runs tests to ensure they pass.
      # - run: npm test
      - run: git status
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply npm update. 
