name: Development

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        persist-credentials: false
    - run: |
        echo "$GITHUB_REPOSITORY"
    - name: 'Automated Version Bump'
      uses: 'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GD_TOKEN }}
        target-branch: 'main'
      with:
        skip-tag:  'true'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run compile:dev
