# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: |
        echo "::group::Environment Information"
        echo "Node Version: $(node -v)"
        echo "NPM: $(npm -v)"
        echo "::endgroup::"
    - run: npm ci
    - run: npm run lint-build
    - run: npm run build --if-present